### ISSUE TITLE
**BROKEN** plugin-sling: thread 'tokio-runtime-worker' panicked at 'called `Option::unwrap()` on a `None` value': src/tasks.rs:235

### ISSUE THREAD

**Issue by 21M4TW** [daywalker90/sling#7]
I get the error with v2.1.1 when starting CLN and I have an existing sling job:

2024-10-21T11:54:38.141Z DEBUG   plugin-sling: Peerchannels refreshed in 1ms
2024-10-21T11:54:38.141Z UNUSUAL plugin-sling: gossip_reader: Malformed gossip_store: 4101 without 256
2024-10-21T11:54:38.141Z DEBUG   plugin-sling: gossip_reader: header error at 46760008:failed to fill whole buffer (not an actual error if buffer could not be filled)
2024-10-21T11:54:38.141Z DEBUG   plugin-sling: gossip_reader: gossip_store read in: 3089ms
2024-10-21T11:54:38.141Z DEBUG   plugin-sling: gossip_reader: found updates:87101 announcements:59103 amounts:59103 deletes/dying:9
2024-10-21T11:54:38.141Z DEBUG   plugin-sling: Peerchannels refreshed in 110ms
2024-10-21T11:54:38.141Z DEBUG   plugin-sling: gossip_reader: post_processing_time: 224ms
2024-10-21T11:54:38.141Z DEBUG   plugin-sling: Reading gossip store done after 3315ms!
2024-10-21T11:54:38.141Z INFO    plugin-sling: 86265 public channels in sling graph after 3319ms!
2024-10-21T11:54:38.141Z DEBUG   plugin-sling: Got * local channels after 3319ms!
2024-10-21T11:54:38.141Z **BROKEN** plugin-sling: thread 'tokio-runtime-worker' panicked at 'called `Option::unwrap()` on a `None` value': src/tasks.rs:235

**Comment by 21M4TW** [comment]
> What CLN version are you running?

v24.08

**Comment by daywalker90** [comment]
This is very strange. The error implies that one of your private channels does not have an alias for the remote side. Could you check your channels (``listpeerchannels``) and see if they all have local and remote aliases like this?:

```json
"alias": {
            "local": "111111x1111x111",
            "remote": "22222x2222x222"
         },
```

**Comment by 21M4TW** [comment]
> This is very strange. The error implies that one of your private channels does not have an alias for the remote side. Could you check your channels (`listpeerchannels`) and see if they all have local and remote aliases like this?:
> 
> ```json
> "alias": {
>             "local": "111111x1111x111",
>             "remote": "22222x2222x222"
>          },
> ```

None of my channels have a remote alias. I have a different peer for each channel.

**Comment by daywalker90** [comment]
That seems like a bug in CLN to me. I need that remote alias to receive sats on that channel. Just to be clear you have private channels where the output of `listpeerchannels` show something like this:

```json
"alias": {
            "local": "111111x1111x111",
         },
```

**Comment by 21M4TW** [comment]
> That seems like a bug in CLN to me. I need that remote alias to receive sats on that channel. Just to be clear you have private channels where the output of `listpeerchannels` show something like this:
> 
> ```json
> "alias": {
>             "local": "111111x1111x111",
>          },
> ```

Correct, this is what I see

**Comment by g00g1** [comment]
I face same issue, `listpeerchannels` has this in my case:

```
         "alias": {
            "local": "1301917x3661151x11865",
            "remote": "16000000x0x0"
         },
```

**Comment by daywalker90** [comment]
> I face same issue, `listpeerchannels` has this in my case:
> 
> ```
>          "alias": {
>             "local": "1301917x3661151x11865",
>             "remote": "16000000x0x0"
>          },
> ```

Also never seen this. Looks like your remote peer is setting a dummy id for that channel? I will open an issue for this on the CLN repo. What version are you using? In the meantime: you can't use that channel for rebalancing and i recommend setting an exception for it with `sling-except-chan`

**Comment by daywalker90** [comment]
I will take a look at it.

**Comment by daywalker90** [comment]
> I use Core Lightning bundled with BTCPay Server, it is `basedon-v24.08.2`.
> 
> I have excluded all problematic channels and restarted the plugin, but I still see this error in the logs.

try v3.0.1

**Comment by g00g1** [comment]
Now I get another error:

```
2025-02-23T22:58:28.954Z DEBUG   plugin-sling-v3.0.1: Killing plugin: disabled itself at init: Version string parse error: basedon-v24.08.2
```

**Comment by daywalker90** [comment]
> basedon-v24.08.2

ah yes you are running a modified cln version that outputs a version string i haven't anticipated ( i use this for backward compatibility). Should be fixed in the upcoming 3.0.2

**Comment by g00g1** [comment]
Thanks you! It fixed this issue and rebalancing started to work again 🥳

**Comment by daywalker90** [comment]
Fixed in v3.0.1
